# Generated by Django 5.2.17 on 2026-08-16 09:11

import catalog.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(blank=True, default='', max_length=100)),
                ('release_year', models.PositiveIntegerField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', validators=[catalog.validators.validate_cover_file])),
                ('listener_count', models.PositiveIntegerField(default=0)),
                ('stream_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='accounts.artistprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lyrics', models.TextField(blank=True, default='')),
                ('genre', models.CharField(blank=True, default='', max_length=100)),
                ('release_year', models.PositiveIntegerField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', validators=[catalog.validators.validate_cover_file])),
                ('audio', models.FileField(upload_to='audio/', validators=[catalog.validators.validate_audio_file])),
                ('duration_seconds', models.PositiveIntegerField(default=180)),
                ('is_early_access', models.BooleanField(default=False)),
                ('listener_count', models.PositiveIntegerField(default=0)),
                ('stream_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='catalog.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='accounts.artistprofile')),
                ('featured_artists', models.ManyToManyField(blank=True, related_name='featured_on_songs', to='accounts.artistprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
