# Generated by Django 5.2.17 on 2026-08-16 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_key', models.CharField(db_index=True, max_length=7)),
                ('unique_listeners', models.PositiveIntegerField(default=0)),
                ('streams', models.PositiveIntegerField(default=0)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='accounts.artistprofile')),
            ],
            options={
                'ordering': ['-payout_amount', 'artist_id'],
                'constraints': [models.UniqueConstraint(fields=('artist', 'month_key'), name='unique_artist_settlement_month')],
            },
        ),
    ]
