import type { Album, Artist, Playlist, RecentPlaylistPlay, Song, StorageSchema, User } from "@/types";

const now = new Date().toISOString();

export const MOCK_ARTIST_ID = "artist-sara-1";
export const MOCK_ALBUM_ID = "album-midnight-echoes";

export const MOCK_USERS: User[] = [
  {
    id: "user-listener-1",
    email: "listener@example.com",
    password: "123456",
    displayName: "Ali Listener",
    username: "ali_listener",
    role: "listener",
    subscription: "silver",
    followerIds: ["user-listener-2"],
    followingUserIds: ["user-artist-1"],
    followingArtistIds: [],
    dailyStreamCount: 12,
    birthDate: "2000-05-15",
    gender: "male",
    createdAt: now,
  },
  {
    id: "user-listener-2",
    email: "basic@example.com",
    password: "123456",
    displayName: "Jamie Basic",
    username: "jamie_basic",
    role: "listener",
    subscription: "basic",
    followerIds: [],
    followingUserIds: ["user-listener-1"],
    followingArtistIds: [],
    dailyStreamCount: 4,
    birthDate: "2002-08-10",
    gender: "female",
    createdAt: now,
  },
  {
    id: "user-artist-1",
    email: "artist@example.com",
    password: "123456",
    displayName: "Sara Artist",
    username: "sara_artist",
    role: "artist",
    subscription: "gold",
    followerIds: ["user-listener-1"],
    followingUserIds: [],
    followingArtistIds: [],
    dailyStreamCount: 0,
    birthDate: "1998-03-20",
    gender: "female",
    createdAt: now,
  },
  {
    id: "user-support-1",
    email: "support@example.com",
    password: "123456",
    displayName: "Reza Support",
    username: "reza_support",
    role: "support",
    subscription: "gold",
    followerIds: [],
    followingUserIds: [],
    followingArtistIds: [],
    dailyStreamCount: 0,
    createdAt: now,
  },
  {
    id: "user-admin-1",
    email: "admin@example.com",
    password: "123456",
    displayName: "System Admin",
    username: "system_admin",
    role: "admin",
    subscription: "gold",
    followerIds: [],
    followingUserIds: [],
    followingArtistIds: [],
    dailyStreamCount: 0,
    createdAt: now,
  },
];

export const MOCK_ARTISTS: Artist[] = [
  {
    id: MOCK_ARTIST_ID,
    userId: "user-artist-1",
    stageName: "Sara Artist",
    bio: "Electronic and ambient music producer.",
    status: "approved",
    isVerified: true,
    totalListeners: 12800,
    totalStreams: 54000,
    createdAt: now,
  },
];

export const MOCK_SONGS: Song[] = [
  {
    id: "song-neon-dreams",
    title: "Neon Dreams",
    artistId: MOCK_ARTIST_ID,
    albumId: MOCK_ALBUM_ID,
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    lyrics: "Neon lights are calling out my name\nRunning through the midnight rain\nEvery dream is painted in bright color\nWe are young and we won't fade away",
    genre: "Electronic",
    releaseYear: 2024,
    featuredArtistIds: [],
    listenerCount: 8200,
    streamCount: 24000,
    durationSeconds: 214,
    createdAt: now,
  },
  {
    id: "song-city-lights",
    title: "City Lights",
    artistId: MOCK_ARTIST_ID,
    albumId: MOCK_ALBUM_ID,
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    lyrics: "City lights above the skyline glow\nEvery street has stories that we know\nHold my hand and walk into the night\nEverything will be alright",
    genre: "Electronic",
    releaseYear: 2024,
    featuredArtistIds: [],
    listenerCount: 6100,
    streamCount: 18000,
    durationSeconds: 192,
    createdAt: now,
  },
  {
    id: "song-solitude",
    title: "Solitude",
    artistId: MOCK_ARTIST_ID,
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    genre: "Ambient",
    releaseYear: 2025,
    featuredArtistIds: [],
    listenerCount: 4300,
    streamCount: 9200,
    durationSeconds: 248,
    isEarlyAccess: true,
    createdAt: now,
  },
  {
    id: "song-aurora-premiere",
    title: "Aurora Premiere",
    artistId: MOCK_ARTIST_ID,
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    genre: "Electronic",
    releaseYear: 2026,
    featuredArtistIds: [],
    listenerCount: 1200,
    streamCount: 800,
    durationSeconds: 231,
    isEarlyAccess: true,
    createdAt: now,
  },
  {
    id: "song-echoes",
    title: "Echoes",
    artistId: MOCK_ARTIST_ID,
    albumId: MOCK_ALBUM_ID,
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    lyrics: "Echoes in the hallway of my mind\nLeave the noise of the world behind\nSoft vibrations fill the empty room\nDancing slowly in the quiet gloom",
    genre: "Electronic",
    releaseYear: 2024,
    featuredArtistIds: [],
    listenerCount: 3900,
    streamCount: 11000,
    durationSeconds: 205,
    createdAt: now,
  },
];

export const MOCK_ALBUMS: Album[] = [
  {
    id: MOCK_ALBUM_ID,
    title: "Midnight Echoes",
    artistId: MOCK_ARTIST_ID,
    genre: "Electronic",
    releaseYear: 2024,
    songIds: ["song-neon-dreams", "song-city-lights", "song-echoes"],
    listenerCount: 15000,
    streamCount: 53000,
    createdAt: now,
  },
];

export const MOCK_PLAYLISTS: Playlist[] = [
  {
    id: "playlist-listener-favorites",
    userId: "user-listener-1",
    name: "Late Night Drive",
    songIds: ["song-neon-dreams", "song-solitude"],
    createdAt: now,
    updatedAt: now,
  },
];

export const MOCK_RECENT_PLAYLIST_PLAYS: RecentPlaylistPlay[] = [
  {
    id: "recent-play-1",
    userId: "user-listener-1",
    playlistId: "playlist-listener-favorites",
    playedAt: now,
  },
];

export const MOCK_SEED_DATA: Partial<StorageSchema> = {
  users: MOCK_USERS,
  artists: MOCK_ARTISTS,
  albums: MOCK_ALBUMS,
  songs: MOCK_SONGS,
  playlists: MOCK_PLAYLISTS,
  recentPlaylistPlays: MOCK_RECENT_PLAYLIST_PLAYS,
};
