# Generated by Django 6.1 on 2026-08-15 09:23

import music.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', validators=[music.validators.validate_cover_file]),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(upload_to='audio/', validators=[music.validators.validate_audio_file]),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', validators=[music.validators.validate_cover_file]),
        ),
    ]
